name: maven-build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checkstyle:
    runs-on: windows-10
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-java@3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml')}}
          restore-keys: |
            maven -
      - run: mvn clean install