CREATE SCHEMA unialbums-backend;
CREATE TABLE our_user(
                         id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         first_name varchar(100) NOT NULL,
                         last_name varchar(100) NOT NULL,
                         login varchar(100) NOT NULL,
                         password varchar(100) NOT NULL,
                         role varchar(100) NOT NULL,
                         avatar varchar(100) NOT NULL
);

CREATE TABLE albums(
                       id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                       user_id  bigint REFERENCES our_user(id),
                       title varchar(100) NOT NULL,
                       artist varchar(100) NOT NULL,
                       cover varchar(100) NOT NULL,
                       tracks_rating int NOT NULL,
                       atmosphere_rating int NOT NULL,
                       bits_rating int NOT NULL,
                       text_rating int)

CREATE TABLE SPRING_SESSION (
                                PRIMARY_ID CHAR(36) NOT NULL,
                                SESSION_ID CHAR(36) NOT NULL,
                                CREATION_TIME BIGINT NOT NULL,
                                LAST_ACCESS_TIME BIGINT NOT NULL,
                                MAX_INACTIVE_INTERVAL INT NOT NULL,
                                EXPIRY_TIME BIGINT NOT NULL,
                                PRINCIPAL_NAME VARCHAR(100),
                                CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
                                           SESSION_PRIMARY_ID CHAR(36) NOT NULL,
                                           ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
                                           ATTRIBUTE_BYTES BYTEA NOT NULL,
                                           CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
                                           CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);