services:
  db:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_DB: unialbums-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: ["-p", "5432"] # Правильный синтаксис для указания порта
    restart: always
  backend:
    image: unialbums-backend-app
    container_name: unialbums-backend-app_container
    expose:
      - "8081"
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql_container:5432/unialbums-backend # Исправленный синтаксис переменных среды
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    restart: always
#    network_mode: bridge # Добавление параметра network_mode для контейнера с бэкендом
