services:
  db:
    container_name: postgresql_container
    image: postgres
    environment:
      POSTGRES_DB: ${SPRING_POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  backend:
    image: tonymal13/unialbums-backend-app:working_version
    container_name: unialbums-backend-app_container
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
      - minio
    restart: always

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9002"
    environment:
      - MINIO_ROOT_USER=${SPRING_MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${SPRING_MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9002:9002"
volumes:
  minio_data: