services:
  db:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_DB: unialbums-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: ["-p", "5432"] # Правильный синтаксис для указания порта
    restart: always
  backend:
    image: tonymal13/unialbums-backend-app:latest
    container_name: unialbums-backend-app_container
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql_container:5432/unialbums-backend # Исправленный синтаксис переменных среды
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
#      - minio
    restart: always
#  minio:
#    image: docker.io/bitnami/minio:2022
#    container_name: minio_container
#    volumes:
#      - ./minio:/data/minio
#    expose:
#      - "9002"
#      - "9000"
#    ports:
#      - "9000:9000"
#      - "9002:9002"
#    environment:
##      SPRING_MINIO_URL: http://minio_container:9002
##      SPRING_MINIO_BUCKET: images
##      SPRING_MINIO_ACCESS_KEY: admin
##      SPRING_MINIO_SECRET_KEY: password
#    - MINIO_ROOT_USER=admin
#    - MINIO_ROOT_PASSWORD=password
#    - MINIO_DEFAULT_BUCKETS=images
#    restart: always
