services:
  db:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_DB: unialbums-backend
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: ["-p", "5432"]
    restart: always
  backend:
    image: tonymal13/unialbums-backend-app:latest
    container_name: unialbums-backend-app_container
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
      - minio
    restart: always

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9002"
    environment:
      - MINIO_ROOT_USER=${SPRING_MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${SPRING_MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9002:9002"
volumes:
  minio_data: