services:
  db:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_DB: unialbums-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: ["-p", "5432"]
    restart: always
  backend:
    image: tonymal13/unialbums-backend-app:deploy_version
    container_name: unialbums-backend-app_container
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql_container:5432/unialbums-backend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
      - minio
    restart: always

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9002"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
#      - MINIO_URL=http://minio:9000
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9002:9002"
volumes:
  minio_data: